#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Z3
Version  : 4.7.1
Release  : 8
URL      : https://github.com/Z3Prover/z3/archive/z3-4.7.1.tar.gz
Source0  : https://github.com/Z3Prover/z3/archive/z3-4.7.1.tar.gz
Summary  : .NET bindings for The Microsoft Z3 SMT solver
Group    : Development/Tools
License  : MIT
Requires: Z3-bin
Requires: Z3-lib
Requires: Z3-license
BuildRequires : cmake
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
muZ: routines related to solving satisfiability of Horn clauses and
solving Datalog programs.

%package bin
Summary: bin components for the Z3 package.
Group: Binaries
Requires: Z3-license

%description bin
bin components for the Z3 package.


%package dev
Summary: dev components for the Z3 package.
Group: Development
Requires: Z3-lib
Requires: Z3-bin
Provides: Z3-devel

%description dev
dev components for the Z3 package.


%package lib
Summary: lib components for the Z3 package.
Group: Libraries
Requires: Z3-license

%description lib
lib components for the Z3 package.


%package license
Summary: license components for the Z3 package.
Group: Default

%description license
license components for the Z3 package.


%prep
%setup -q -n z3-z3-4.7.1
pushd ..
cp -a z3-z3-4.7.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529093336
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make  %{?_smp_mflags}
popd
mkdir clr-build-avx2
pushd clr-build-avx2
export CFLAGS="$CFLAGS -O3 -march=haswell "
export FCFLAGS="$CFLAGS -O3 -march=haswell "
export FFLAGS="$CFLAGS -O3 -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64/haswell -DCMAKE_INSTALL_LIBDIR=/usr/lib64/haswell -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make  %{?_smp_mflags}  || :
popd

%install
export SOURCE_DATE_EPOCH=1529093336
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/Z3
cp LICENSE.txt %{buildroot}/usr/share/doc/Z3/LICENSE.txt
mkdir -p %{buildroot}/usr/lib64/haswell/avx512_1
pushd clr-build-avx2
%make_install  || :
mv %{buildroot}/usr/lib64/*so* %{buildroot}/usr/lib64/haswell/ || :
popd
rm -f %{buildroot}/usr/bin/*
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/haswell/cmake/z3/Z3Config.cmake
/usr/lib64/haswell/cmake/z3/Z3Targets-relwithdebinfo.cmake
/usr/lib64/haswell/cmake/z3/Z3Targets.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/z3

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/cmake/z3/Z3Config.cmake
/usr/lib64/cmake/z3/Z3Targets-relwithdebinfo.cmake
/usr/lib64/cmake/z3/Z3Targets.cmake
/usr/lib64/haswell/libz3.so
/usr/lib64/libz3.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libz3.so.4.7
/usr/lib64/haswell/libz3.so.4.7.1.0
/usr/lib64/libz3.so.4.7
/usr/lib64/libz3.so.4.7.1.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/Z3/LICENSE.txt
